version: '2'

services:
  webserver:
    build:
     context: ./webserver
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
    links:
      - "apiengine"

  apiengine:
    build:
      context: ./apiengine
    expose:
      - "8081"
    environment:
      TZ: Asia/Tokyo
    links:
      - "database" 

  database:
    image:
      postgres:12.1
    expose:
      - "5432"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:
    driver: local
