apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001 
  annotations:
    volume.beta.kubernets.io/storage-class: "slow"
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv0001"
  annotations:
    volume.beta.kubernets.io/storage-class: "slow"
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.201
    path: /

