apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database 
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:12.1
          volumeMounts:
            - name: dbdata
            - mountPath: "/var/lib/postgresql/data"
      volumeClaimTemplates:
      - metadata:
          name: dbdata
        spec:
          accessModes:
          - ReadWriteOnce:
          volumeMode: Filesystem
          resource:
            requests:
              storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: database

