#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#    name: gp2 
#provisioner: kubernetes.io/aws-ebs
#parameters:
#  type: gp2
#reclaimPolicy: Retain
#allowVolumeExpansion: true
#volumeBindingMode: Immediate
#
#---
#apiVersion: "v1"
#kind: "PersistentVolume"
#metadata:
#  name: "pv0001"
#spec:
#  capacity:
#    storage: "1Gi"
#  accessModes:
#    - ReadWriteOnce
#  awsElasticBlockStore:
#    fsType: "ext4"
#    volumeID: "vol-0544b00c0627f2ec3"
#
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001 
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp

